# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqgXyhrbt_eiKGqzv0qcD5NxuTHCgYGr
"""

import streamlit as st
import joblib
import numpy as np

# Load model
model = joblib.load("best_model.pkl")  # path to your saved model

# Page setup
st.set_page_config(page_title="❤️ Heart Disease Predictor", page_icon="❤️", layout="centered")

# App title
st.markdown("<h1 style='text-align: center; color: #e63946;'>Heart Disease Prediction App</h1>", unsafe_allow_html=True)
st.write("### Enter the patient's details below:")

# Create input fields
col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", min_value=1, max_value=120, value=45)
    sex = st.selectbox("Sex", ["Male", "Female"])
    cp = st.selectbox("Chest Pain Type (0–3)", [0, 1, 2, 3])
    trestbps = st.number_input("Resting Blood Pressure", min_value=80, max_value=200, value=120)
    chol = st.number_input("Cholesterol", min_value=100, max_value=600, value=200)
    fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl", [0, 1])

with col2:
    restecg = st.selectbox("Resting ECG (0–2)", [0, 1, 2])
    thalach = st.number_input("Max Heart Rate Achieved", min_value=60, max_value=220, value=150)
    exang = st.selectbox("Exercise Induced Angina", [0, 1])
    oldpeak = st.number_input("ST Depression", min_value=0.0, max_value=10.0, value=1.0)
    slope = st.selectbox("Slope (0–2)", [0, 1, 2])
    ca = st.selectbox("Number of Major Vessels (0–3)", [0, 1, 2, 3])
    thal = st.selectbox("Thalassemia (1–3)", [1, 2, 3])

# Predict button
if st.button("🔍 Predict"):
    sex_val = 1 if sex == "Male" else 0
    features = np.array([[age, sex_val, cp, trestbps, chol, fbs, restecg, thalach,
                          exang, oldpeak, slope, ca, thal]])

    prediction = model.predict(features)[0]
    result = "💔 High Risk of Heart Disease" if prediction == 1 else "💖 Low Risk (Healthy)"

    st.markdown(
        f"<h3 style='text-align: center; color: {'#e63946' if prediction==1 else '#2a9d8f'};'>{result}</h3>",
        unsafe_allow_html=True
    )

# Footer
st.markdown("---")
st.markdown("<p style='text-align: center;'>Developed with ❤️ using Streamlit by kanika</p>", unsafe_allow_html=True)

