# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCJ6Q67h5PMZS0w5i4Jj5kVS1tNUyX4p
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
import joblib
import numpy as np
import uvicorn

# Initialize app
app = FastAPI()

# Allow frontend connection (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # or specify your frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load your trained model
model = joblib.load("best_model.pkl")  # path to your saved model

@app.get("/")
def root():
    return {"message": "Heart Disease Prediction API is running"}

# POST route for prediction
@app.post("/predict")
async def predict(request: Request):
    data = await request.json()  # receive JSON from frontend
    # Example expected input keys (adjust based on your model features)
    features = [
        data["age"],
        data["sex"],
        data["cp"],
        data["trestbps"],
        data["chol"],
        data["fbs"],
        data["restecg"],
        data["thalach"],
        data["exang"],
        data["oldpeak"],
        data["slope"],
        data["ca"],
        data["thal"]
    ]

    # Convert to NumPy array
    input_data = np.array(features).reshape(1, -1)

    # Make prediction
    prediction = model.predict(input_data)[0]
    result = "Heart Disease" if prediction == 1 else "No Heart Disease"

    return {"prediction": result}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

